export const TargetingType = {
    SINGLE_TARGET: 'SINGLE_TARGET',
    AOE_AROUND_SELF: 'AOE_AROUND_SELF',
    AOE_CARDINAL_DIRECTION: 'AOE_CARDINAL_DIRECTION',
    AOE_FROM_POINT: 'AOE_FROM_POINT',
    AOE_FROM_POINT_WITHIN_RANGE: 'AOE_FROM_POINT_WITHIN_RANGE',
    SELF: 'SELF'
};